// SPDX-FileCopyrightText: 2023 Janet Blackquill <uhhadd@gmail.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

package BallCore.Reinforcements

import org.bukkit.Material
import org.bukkit.Material.*

object BlockSets:
  val campfires: Set[Material] = Set(
    CAMPFIRE,
    SOUL_CAMPFIRE
  )
  val igniters: Set[Material] = Set(
    FLINT_AND_STEEL,
    FIRE_CHARGE
  )
  val candles: Set[Material] = Set(
    CANDLE,
    CANDLE_CAKE,
    CYAN_CANDLE,
    CYAN_CANDLE_CAKE,
    BLACK_CANDLE,
    BLACK_CANDLE_CAKE,
    BLUE_CANDLE,
    BLUE_CANDLE_CAKE,
    BROWN_CANDLE,
    BROWN_CANDLE_CAKE,
    GRAY_CANDLE,
    GRAY_CANDLE_CAKE,
    GREEN_CANDLE,
    GREEN_CANDLE_CAKE,
    LIGHT_BLUE_CANDLE,
    LIGHT_BLUE_CANDLE_CAKE,
    LIGHT_GRAY_CANDLE,
    LIGHT_GRAY_CANDLE_CAKE,
    LIME_CANDLE,
    LIME_CANDLE_CAKE,
    MAGENTA_CANDLE,
    MAGENTA_CANDLE_CAKE,
    ORANGE_CANDLE,
    ORANGE_CANDLE_CAKE,
    PINK_CANDLE,
    PINK_CANDLE_CAKE,
    PURPLE_CANDLE,
    PURPLE_CANDLE_CAKE,
    RED_CANDLE,
    RED_CANDLE_CAKE,
    WHITE_CANDLE,
    WHITE_CANDLE_CAKE,
    YELLOW_CANDLE,
    YELLOW_CANDLE_CAKE
  )
  val beehiveHarvestingTools: Set[Material] = Set(
    SHEARS,
    GLASS_BOTTLE
  )
  val beehives: Set[Material] = Set(
    BEEHIVE,
    BEE_NEST
  )
  val logs: Set[Material] = Set(
    ACACIA_LOG,
    BIRCH_LOG,
    DARK_OAK_LOG,
    JUNGLE_LOG,
    OAK_LOG,
    SPRUCE_LOG
  )
  val farmlandableBlocks: Set[Material] = Set(
    GRASS_BLOCK,
    DIRT,
    COARSE_DIRT,
    DIRT_PATH
  )
  val copperBlocks: Set[Material] = Set(
    COPPER_BLOCK,
    EXPOSED_COPPER,
    WEATHERED_COPPER,
    OXIDIZED_COPPER,
    CUT_COPPER,
    EXPOSED_CUT_COPPER,
    WEATHERED_CUT_COPPER,
    OXIDIZED_CUT_COPPER,
    CUT_COPPER_STAIRS,
    EXPOSED_CUT_COPPER_STAIRS,
    WEATHERED_CUT_COPPER_STAIRS,
    OXIDIZED_CUT_COPPER_STAIRS,
    CUT_COPPER_SLAB,
    EXPOSED_CUT_COPPER_SLAB,
    WEATHERED_CUT_COPPER_SLAB,
    OXIDIZED_CUT_COPPER_SLAB,
    WAXED_COPPER_BLOCK,
    WAXED_EXPOSED_COPPER,
    WAXED_WEATHERED_COPPER,
    WAXED_OXIDIZED_COPPER,
    WAXED_CUT_COPPER,
    WAXED_EXPOSED_CUT_COPPER,
    WAXED_WEATHERED_CUT_COPPER,
    WAXED_OXIDIZED_CUT_COPPER,
    WAXED_CUT_COPPER_STAIRS,
    WAXED_EXPOSED_CUT_COPPER_STAIRS,
    WAXED_WEATHERED_CUT_COPPER_STAIRS,
    WAXED_OXIDIZED_CUT_COPPER_STAIRS,
    WAXED_CUT_COPPER_SLAB,
    WAXED_EXPOSED_CUT_COPPER_SLAB,
    WAXED_WEATHERED_CUT_COPPER_SLAB,
    WAXED_OXIDIZED_CUT_COPPER_SLAB
  )
