# SPDX-FileCopyrightText: 2022 Janet Blackquill <uhhadd@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later
name: CivCubed
version: "0.1"
main: CivCubed.Main
description: Hub plugin of CivBalls
authors: [Janet Blackquill]
website: https://github.com/BlueMoonVineyard/CivCubed
api-version: "1.20"
folia-supported: true
dependencies:
  server:
    CivCubedDependencyPlugin:
      load: BEFORE
      required: true
      join-classpath: true
    CivCubedCommonCode:
      load: BEFORE
      required: true
      join-classpath: true
    ProtocolLib:
      load: BEFORE
      required: false
      join-classpath: false
    ProtocolSupport:
      load: BEFORE
      required: false
      join-classpath: false
    ViaVersion:
      load: BEFORE
      required: false
      join-classpath: false
    ViaBackwards:
      load: BEFORE
      required: false
      join-classpath: false
    ViaRewind:
      load: BEFORE
      required: false
      join-classpath: false
    Geyser-Spigot:
      load: BEFORE
      required: false
      join-classpath: false