name: BallCore
version: 0.1
main: BallCore.Main
description: Core plugin of CivBalls
authors: [Janet Blackquill]
website: https://github.com/BlueMoonVineyard/BallCore
api-version: 1.13
depend:
  - Slimefun