# SPDX-FileCopyrightText: 2022 Janet Blackquill <uhhadd@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later
name: BallCore
version: 0.1
main: BallCore.Main
description: Core plugin of CivBalls
authors: [ Janet Blackquill ]
website: https://github.com/BlueMoonVineyard/BallCore
folia-supported: true
api-version: 1.13
depend:
  - BallCoreDependencyPlugin
  - BallCoreCommonCode
softdepend:
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Geyser-Spigot
commands:
  groups:
    description: View the groups UI
  plants:
    description: View the list of plants
  cheat:
    description: Cheats in a custom item
  group:
    description: Changes your chat channel to a specific group
    aliases: [ g ]
  global:
    description: Changes your chat channel to global chat
  polyhedra:
    description: "TODO: polyhedra editor"
  local:
    description: Changes your chat channel to local chat
  done:
    description: Completes the editor
permissions:
  ballcore.cheat:
    description: Allows using /cheat
    default: op