# SPDX-FileCopyrightText: 2023 Janet Blackquill <uhhadd@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later
name: CivCubedDependencyPlugin
version: "0.1"
main: CivCubedDependencyPlugin.Main
description: Dependency plugin of CivBalls
authors: [Janet Blackquill]
website: https://github.com/BlueMoonVineyard/CivCubed
api-version: "1.20"
folia-supported: true
