name: CivCubedCommonCode
version: "0.1"
main: CivCubed.CommonCode.PaperPlugin
description: Common code plugin of CivBalls
authors: [Janet Blackquill]
website: https://github.com/BlueMoonVineyard/CivCubed
api-version: "1.20"
folia-supported: true
dependencies:
  server:
    CivCubedDependencyPlugin:
      load: BEFORE
      required: true
      join-classpath: true
