name: BallCore CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Run tests
      run: sbt coverage test
    # - name: Coverage report
    #   run: sbt coverageReport
    # - name: Upload coverage to Codecov
    #   uses: codecov/codecov-action@v3
    #   with:
    #     fail_ci_if_error: true
    - name: Assemble dependency plugin
      run: sbt dependencyPlugin/assembly
    - name: Package main plugin
      run: sbt actualPlugin/package
    - name: Package hub plugin
      run: sbt hubPlugin/package
    - name: Move jars
      run: |
        cp ./target/scala-3.3.0-RC3/ballcore_3-0.1.0-SNAPSHOT.jar BallCore.jar
        cp ./dependency-plugin/target/scala-3.3.0-RC3/BallCoreDependencyPlugin.jar BallCoreDependencyPlugin.jar
        cp ./hub-plugin/target/scala-3.3.0-RC3/ballcorehub_3-0.1.0-SNAPSHOT.jar BallCoreHub.jar
    - name: Update jars
      uses: andelf/nightly-release@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ci
        name: 'Continuous integration $$'
        prerelease: true
        files: |
          ./BallCoreDependencyPlugin.jar
          ./BallCore.jar
          ./BallCoreHub.jar
