# SPDX-FileCopyrightText: 2023 Janet Blackquill <uhhadd@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

name: BallCore CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: "shitty password"
          POSTGRES_DB: civcubed
          POSTGRES_USER: civcubed
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Run tests
      run: sbt coverage test
    - name: Coverage report
      run: sbt coverageReport
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: false
    - name: Assemble dependency plugin
      run: sbt dependencyPlugin/assembly
    - name: Package common code plugin
      run: sbt commonCode/package
    - name: Package main plugin
      run: sbt actualPlugin/package
    - name: Package hub plugin
      run: sbt hubPlugin/package
    - name: Package velocity plugin
      run: sbt velocityPlugin/package
    - name: Move jars
      run: |
        cp ./target/scala-3.3.1/ballcore_3-0.1.0-SNAPSHOT.jar BallCore.jar
        cp ./dependency-plugin/target/scala-3.3.1/BallCoreDependencyPlugin.jar BallCoreDependencyPlugin.jar
        cp ./hub-plugin/target/scala-3.3.1/ballcorehub_3-0.1.0-SNAPSHOT.jar BallCoreHub.jar
        cp ./common-code/target/scala-3.3.1/ballcorecommoncode_3-0.1.0-SNAPSHOT.jar BallCoreCommonCode.jar
        cp ./velocity-plugin/target/scala-3.3.1/ballcorevelocity_3-0.1.0-SNAPSHOT.jar BallCoreVelocityPlugin.jar
    - name: Update jars
      uses: andelf/nightly-release@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ci
        name: 'Continuous integration $$'
        prerelease: true
        files: |
          ./BallCoreDependencyPlugin.jar
          ./BallCore.jar
          ./BallCoreHub.jar
          ./BallCoreCommonCode.jar
          ./BallCoreVelocityPlugin.jar
